from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def close_bt(self):
        MainWindow.quit()
        MainWindow.destroy()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1345, 903)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Tab.setGeometry(QtCore.QRect(20, 220, 351, 641))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Tab.setFont(font)
        self.Tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.Tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Tab.setObjectName("Tab")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.Tab.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Tab.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.Tab.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.Tab.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.Tab.addTab(self.tab_5, "")
        self.info_frame = QtWidgets.QFrame(self.centralwidget)
        self.info_frame.setGeometry(QtCore.QRect(20, 10, 731, 181))
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.info_frame.setObjectName("info_frame")
        self.GO_lb = QtWidgets.QLabel(self.info_frame)
        self.GO_lb.setGeometry(QtCore.QRect(350, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.GO_lb.setFont(font)
        self.GO_lb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GO_lb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.GO_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.GO_lb.setObjectName("GO_lb")
        self.BIN_lb = QtWidgets.QLabel(self.info_frame)
        self.BIN_lb.setGeometry(QtCore.QRect(20, 70, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.BIN_lb.setFont(font)
        self.BIN_lb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BIN_lb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.BIN_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.BIN_lb.setObjectName("BIN_lb")
        self.SANG_lb = QtWidgets.QLabel(self.info_frame)
        self.SANG_lb.setGeometry(QtCore.QRect(350, 70, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.SANG_lb.setFont(font)
        self.SANG_lb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SANG_lb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SANG_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.SANG_lb.setObjectName("SANG_lb")
        self.ID_txt = QtWidgets.QTextEdit(self.info_frame)
        self.ID_txt.setGeometry(QtCore.QRect(110, 20, 131, 31))
        self.ID_txt.setObjectName("ID_txt")
        self.BIN_txt = QtWidgets.QTextEdit(self.info_frame)
        self.BIN_txt.setGeometry(QtCore.QRect(110, 70, 131, 31))
        self.BIN_txt.setObjectName("BIN_txt")
        self.ID_lb = QtWidgets.QLabel(self.info_frame)
        self.ID_lb.setGeometry(QtCore.QRect(20, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.ID_lb.setFont(font)
        self.ID_lb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ID_lb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ID_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.ID_lb.setObjectName("ID_lb")
        self.GO_txt = QtWidgets.QTextEdit(self.info_frame)
        self.GO_txt.setGeometry(QtCore.QRect(440, 20, 131, 31))
        self.GO_txt.setObjectName("GO_txt")
        self.SANG_txt = QtWidgets.QTextEdit(self.info_frame)
        self.SANG_txt.setGeometry(QtCore.QRect(440, 70, 131, 31))
        self.SANG_txt.setObjectName("SANG_txt")
        self.Save_bt = QtWidgets.QPushButton(self.info_frame)
        self.Save_bt.setGeometry(QtCore.QRect(440, 110, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Save_bt.setFont(font)
        self.Save_bt.setObjectName("Save_bt")
        self.Push_bt = QtWidgets.QPushButton(self.info_frame)
        self.Push_bt.setGeometry(QtCore.QRect(580, 110, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Push_bt.setFont(font)
        self.Push_bt.setObjectName("Push_bt")
        self.MG_bt = QtWidgets.QPushButton(self.info_frame)
        self.MG_bt.setGeometry(QtCore.QRect(300, 110, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.MG_bt.setFont(font)
        self.MG_bt.setObjectName("MG_bt")
        self.money_frame = QtWidgets.QFrame(self.centralwidget)
        self.money_frame.setGeometry(QtCore.QRect(770, 10, 561, 181))
        self.money_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.money_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.money_frame.setObjectName("money_frame")
        self.RM_lb = QtWidgets.QLabel(self.money_frame)
        self.RM_lb.setGeometry(QtCore.QRect(20, 70, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.RM_lb.setFont(font)
        self.RM_lb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RM_lb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.RM_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.RM_lb.setObjectName("RM_lb")
        self.CM_lb = QtWidgets.QLabel(self.money_frame)
        self.CM_lb.setGeometry(QtCore.QRect(20, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.CM_lb.setFont(font)
        self.CM_lb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CM_lb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.CM_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.CM_lb.setObjectName("CM_lb")
        self.CH_lb = QtWidgets.QLabel(self.money_frame)
        self.CH_lb.setGeometry(QtCore.QRect(20, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.CH_lb.setFont(font)
        self.CH_lb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CH_lb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.CH_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.CH_lb.setObjectName("CH_lb")
        self.CM_txt = QtWidgets.QTextEdit(self.money_frame)
        self.CM_txt.setGeometry(QtCore.QRect(110, 20, 131, 31))
        self.CM_txt.setObjectName("CM_txt")
        self.RM_txt = QtWidgets.QTextEdit(self.money_frame)
        self.RM_txt.setGeometry(QtCore.QRect(110, 70, 131, 31))
        self.RM_txt.setObjectName("RM_txt")
        self.CH_bt = QtWidgets.QTextEdit(self.money_frame)
        self.CH_bt.setGeometry(QtCore.QRect(110, 120, 131, 31))
        self.CH_bt.setObjectName("CH_bt")
        self.print_bt = QtWidgets.QPushButton(self.money_frame)
        self.print_bt.setGeometry(QtCore.QRect(290, 20, 121, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.print_bt.setFont(font)
        self.print_bt.setObjectName("print_bt")
        self.close_bt = QtWidgets.QPushButton(self.money_frame)
        self.close_bt.setGeometry(QtCore.QRect(420, 20, 121, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.close_bt.setFont(font)
        self.close_bt.setObjectName("close_bt")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(380, 220, 951, 641))
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.main_frame.setObjectName("main_frame")
        self.columnView = QtWidgets.QColumnView(self.main_frame)
        self.columnView.setGeometry(QtCore.QRect(10, 10, 931, 621))
        self.columnView.setObjectName("columnView")
        self.money_frame.raise_()
        self.main_frame.raise_()
        self.info_frame.raise_()
        self.Tab.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1345, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Tab.setTabText(self.Tab.indexOf(self.tab_1), _translate("MainWindow", "식당판매"))
        self.Tab.setTabText(self.Tab.indexOf(self.tab_2), _translate("MainWindow", "매점판매"))
        self.Tab.setTabText(self.Tab.indexOf(self.tab_3), _translate("MainWindow", "장의용품"))
        self.Tab.setTabText(self.Tab.indexOf(self.tab_4), _translate("MainWindow", "상복"))
        self.Tab.setTabText(self.Tab.indexOf(self.tab_5), _translate("MainWindow", "기타"))
        self.GO_lb.setText(_translate("MainWindow", "고인명"))
        self.BIN_lb.setText(_translate("MainWindow", "빈소"))
        self.SANG_lb.setText(_translate("MainWindow", "상주명"))
        self.ID_lb.setText(_translate("MainWindow", "ID"))
        self.Save_bt.setText(_translate("MainWindow", "저장"))
        self.Push_bt.setText(_translate("MainWindow", "불러오기"))
        self.MG_bt.setText(_translate("MainWindow", "재고관리"))
        self.RM_lb.setText(_translate("MainWindow", "받은금액"))
        self.CM_lb.setText(_translate("MainWindow", "수납금액"))
        self.CH_lb.setText(_translate("MainWindow", "거스름돈"))
        self.print_bt.setText(_translate("MainWindow", "인쇄"))
        self.close_bt.setText(_translate("MainWindow", "닫기"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
